---

- name: Set up hosted FMD Server
  hosts:
    - hosted
  become: true
  become_user: root

  tasks:

    - name: Deploy hosted beta server
      ansible.builtin.include_role:
        name: fmd-server
      vars:
        fmd_server_domain: server-beta.fmd-foss.org
        fmd_server_env: beta
        fmd_server_binary: "/package/server/fmd-server-v0.12.0.zip"

    # TODO: prod, fmd.nulide.de
