---

- name: Set up hosted FMD Server
  hosts:
    - hosted
  become: true
  become_user: root

  tasks:

    - name: Deploy hosted edge server
      ansible.builtin.include_role:
        name: fmd-server
      vars:
        fmd_server_domain: server-edge.fmd-foss.org
        fmd_server_env: edge
        fmd_server_zip: "fmd-server-v0.14.2.zip"
        fmd_server_metrics_port: "9101"
        # Public value. Only to force users to acknowledge that the edge server comes with no guarantees.
        fmd_server_registration_token: ""

    - name: Deploy hosted prod server
      ansible.builtin.include_role:
        name: fmd-server
      vars:
        fmd_server_domain: server.fmd-foss.org
        fmd_server_env: prod
        fmd_server_zip: "fmd-server-v0.14.1.zip"
        fmd_server_metrics_port: "9102"
        fmd_server_registration_token: ""
