# Jail for FMD Server

[fmd-server]
enabled = true
# https://man.archlinux.org/man/jail.conf.5#systemd
backend = systemd[journalflags=1]

# The SYSLOG_IDENTIFIER is the same for all environments.
# This allows us to have a single jail for both prod and edge.
# If you want per-environment jails, use _SYSTEMD_UNIT=fmd-server-prod.service.
journalmatch = SYSLOG_IDENTIFIER=fmd-server

# Goal: block cross-account login attempts from a single IP.

# Balance availability for legitimate users who mis-type their password against brute-force protections.
# On the application level, users already get a push notification for blocked login attempts.
# Thus weaker defaults are acceptable.
bantime  = 4h
findtime = 4h

# Give an IP more attempts. On the application level, 5 attempts are allowed, followed by a 10 minute block.
# Thus allow a legitimate user to try again after this block, without being blocked by fail2ban.
maxretry = 15
