server {
    listen 80;
    listen [::]:80;
    server_name {{ fmd_server_domain }};
    server_tokens off;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/acme/;
        allow all;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

upstream fmdserver{{ fmd_server_env }} {
    # curl --unix-socket /run/fmd-server-{{ fmd_server_env }}/fmd.sock http://localhost
    server unix:/run/fmd-server-{{ fmd_server_env }}/fmd.sock;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    server_name {{ fmd_server_domain }};

    server_tokens off;

    ssl_certificate /etc/letsencrypt/live/{{ fmd_server_domain }}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/{{ fmd_server_domain }}/privkey.pem;

    # https://ssl-config.mozilla.org/#server=nginx&version=1.27.3&config=intermediate&openssl=3.4.0&guideline=5.7
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ecdh_curve X25519:prime256v1:secp384r1;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-CHACHA20-POLY1305;
    ssl_prefer_server_ciphers off;

    # Security headers
    # Other headers (CSP, etc) are added by FMD itself.
    add_header Strict-Transport-Security "max-age=63072000" always;

    # Increase upload body size, e.g. for images
    client_max_body_size 20m;

    location / {
        proxy_set_header Connection "upgrade";
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;

        proxy_buffering off;
        proxy_request_buffering off;

        proxy_pass http://fmdserver{{ fmd_server_env }};
        # proxy_pass  http://127.0.0.1:8080/;
    }
}
