# MANAGED BY ANSIBLE
# Use stricter values than fail2ban's defaults.

[sshd]
enabled = true

# how long a host is banned
bantime  = 1d

# window to look for failures in
findtime = 6h

# number of failures before getting banned
maxretry = 5
