server {
    listen 80;
    listen [::]:80;

    server_name *.fmd-foss.org fmd.nulide.de;

    server_name_in_redirect off;
    server_tokens off;

    location ^~ /.well-known/acme-challenge/ {
        root    /var/www/acme/;
        allow all;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
