server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;

    server_name grafana.fmd-foss.org;

    server_tokens off;

    ssl_certificate /etc/letsencrypt/live/grafana.fmd-foss.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/grafana.fmd-foss.org/privkey.pem;

    ssl_protocols TLSv1.3;

    # Security headers
    # Grafana should set the rest itself
    add_header Strict-Transport-Security "max-age=63072000" always;

    location / {
        proxy_set_header Connection "upgrade";
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;

        proxy_pass http://127.0.0.1:3000/;
    }
}
